// Copyright Guy (Drakynfly) Lundvall. All Rights Reserved.

#pragma once

#include "Engine/DataAsset.h"
#include "FaerieItemSource.h"
#include "FaerieItemDataFwd.h"

#include "StructUtils/InstancedStruct.h"

#include "FaerieItemAsset.generated.h"

class UFaerieItemTemplate;

/**
 * A basic item definition. Used to generate generic items with no procedural data.
 */
UCLASS(BlueprintType, Const)
class FAERIEITEMDATA_API UFaerieItemAsset : public UPrimaryDataAsset, public IFaerieItemSource
{
	GENERATED_BODY()

public:
	//~ UObject
#if WITH_EDITORONLY_DATA
	virtual void GetAssetRegistryTagMetadata(TMap<FName, FAssetRegistryTagMetadata>& OutMetadata) const override;
#endif

	virtual void GetAssetRegistryTags(FAssetRegistryTagsContext Context) const override;
	virtual void PreSave(FObjectPreSaveContext SaveContext) override;
	virtual void PostLoad() override;

#if WITH_EDITOR
	virtual EDataValidationResult IsDataValid(FDataValidationContext& Context) const override;
#endif
	//~ UObject

	//~ IFaerieItemSource
	virtual bool CanBeMutable() const override;
	virtual Faerie::ItemData::FGetInstanceResult CreateItemStack(const FFaerieItemInstancingContext& Context) const override;
	//~ IFaerieItemSource

private:
#if WITH_EDITOR
	FFaerieItemInstance CreateReferencingInstance_Editor(TNotNull<UObject*> InstanceOuter) const;
#endif
	FFaerieItemInstance CreateReferencingInstance_Runtime(TNotNull<const UObject*> WorldContextObj) const;

public:
	// Get the immutable template item this asset holds.
	UFUNCTION(BlueprintCallable, Category = "Faerie|ItemAsset")
	const UFaerieItem* GetAssetTemplateItem() const { return Item; }

	// Get the item instance this asset represents. By default, this will return the immutable asset if possible.
	// If the item needs to allow changes, set Mutability to Mutable.
	FFaerieItemInstance GetTemplateInstance() const;

protected:
	UPROPERTY(VisibleAnywhere, DuplicateTransient, Category = "ItemAsset")
	TObjectPtr<UFaerieItem> Item;

#if WITH_EDITORONLY_DATA
	/*
	 * A version number to associate with items generated by this asset.
	 * Items generated with an older version with fail validation, allowing loaders to determine if an instance
	 * is out-dated.
	 * Incrementing this is left to the user.
	 */
	UPROPERTY(EditInstanceOnly, DuplicateTransient, Category = "ItemAsset")
	int32 AssetVersion = 1;

	UPROPERTY(EditInstanceOnly, Category = "ItemAsset", meta = (ExcludeBaseStruct))
	TArray<TInstancedStruct<FFaerieMassFragment>> Fragments;

	// Item template, used to verify that the generated item follows an expected pattern.
	UPROPERTY(EditInstanceOnly, Category = "ItemAsset")
	TObjectPtr<UFaerieItemTemplate> Template;

	UPROPERTY(EditInstanceOnly, Category = "ItemAsset")
	EFaerieItemInstancingMutability InstanceMutability = EFaerieItemInstancingMutability::Automatic;

public:
	// If this is enabled, this will be a template that will appear in the template section when creating a new asset.
	UPROPERTY(EditInstanceOnly, Category = "ItemAsset", AssetRegistrySearchable)
	bool IsEditorTemplate = false;

	UPROPERTY(VisibleAnywhere, Instanced, Category = "Thumbnail")
	TObjectPtr<class UThumbnailInfo> ThumbnailInfo;
#endif
};